locastic_sylius_catalog_promotion_plugin_admin_catalog:
    resource: |
        alias: locastic_sylius_catalog_promotion_plugin.catalog_promotion
        section: admin
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: locastic_sylius_catalog_promotion_plugin_admin_catalog_promotion
        vars:
            all:
                subheader: locastic_sylius_catalog_promotion_plugin.ui.catalogs
                templates:
                    form: LocasticSyliusCatalogPromotionPlugin:CatalogPromotion:_form.html.twig
            index:
                icon: 'file image outline'
    type: sylius.resource