locastic_sylius_catalog_promotion_plugin_admin_catalog_promotion:
    resource: 'catalog_promotion.yml'

locastic_sylius_catalog_promotion_plugin_admin_catalog_promotion_group:
    resource: 'catalog_promotion_group.yml'
    prefix: /catalog-promotions
