locastic_sylius_catalog_promotion_plugin_admin_catalog_promotion:
    resource: |
        alias: locastic_sylius_catalog_promotion_plugin.catalog_promotion
        section: admin
        templates: SyliusAdminBundle:Crud
        redirect: index
        grid: locastic_sylius_catalog_promotion_plugin_admin_catalog_promotion
        vars:
            all:
                subheader: locastic_sylius_catalog_promotion_plugin.ui.catalogs
                templates:
                    form:  "@SyliusCatalogPromotionPlugin/CatalogPromotion/Crud/_form.html.twig"
            index:
                icon: 'file image outline'
    type: sylius.resource

locastic_sylius_catalog_promotion_plugin_admin_catalog_promotion_partial_show:
    path: /catalog-promotions/_partials/{id}
    methods: [GET]
    defaults:
        _controller: locastic_sylius_catalog_promotion_plugin.controller.catalog_promotion:showAction
        _sylius:
            template: $template
            vars: $vars
            permission: true