services:
#catalog promotion
    locastic.sylius_catalog_promotion_plugin.form.type.catalog_promotion:
        class: Locastic\SyliusCatalogPromotionPlugin\Form\Type\CatalogPromotionType
        arguments:
            - '%locastic_sylius_catalog_promotion_plugin.model.catalog_promotion.class%'
            - ['locastic']
        tags:
            - { name: form.type }

    locastic.sylius_catalog_promotion_plugin.form.type.catalog_promotion_translation:
        class: Locastic\SyliusCatalogPromotionPlugin\Form\Type\CatalogPromotionTranslationType
        arguments:
            - '%locastic_sylius_catalog_promotion_plugin.model.catalog_promotion_translation.class%'
            - ['locastic']
        tags:
            - { name: form.type }

    locastic.sylius_catalog_promotion_plugin.form.type.catalog_promotion_group:
        class: Locastic\SyliusCatalogPromotionPlugin\Form\Type\CatalogPromotionGroupType
        arguments:
            - '%locastic_sylius_catalog_promotion_plugin.model.catalog_promotion_group.class%'
            - ['locastic']
            - "@sylius.repository.product_variant"
        tags:
            - { name: form.type }
#promo actions
    locastic.sylius_catalog_promotion_plugin.form.type.promotion_action_choice_type:
        class: Locastic\SyliusCatalogPromotionPlugin\Form\Type\PromotionActionChoiceType
        arguments:
#            - '%locastic_sylius_catalog_promotion_plugin.promotion_actions%'
        tags:
            - { name: form.type, alias: Locastic\SyliusCatalogPromotionPlugin\Form\Type\PromotionActionChoiceType }

    locastic.sylius_catalog_promotion_plugin.form.type.promotion_action_type:
        class: Locastic\SyliusCatalogPromotionPlugin\Form\Type\PromotionActionType
        arguments:
            - '%locastic_sylius_catalog_promotion_plugin.model.promotion_action.class%'
            - ['locastic']
            - '@locastic_sylius_catalog_promotion_plugin.form_registry.promotion_action_executor'
        tags:
            - { name: form.type, alias: Locastic\SyliusCatalogPromotionPlugin\Form\Type\PromotionActionType }