services:
    locastic.sylius_catalog_promotion_plugin.form.type.catalog_promotion:
        class: Locastic\SyliusCatalogPromotionPlugin\Form\Type\CatalogPromotionType
        arguments:
            - '%locastic_sylius_catalog_promotion_plugin.model.catalog_promotion.class%'
            - ['sylius']
        tags:
            - { name: form.type }

    locastic.sylius_catalog_promotion_plugin.form.type.catalog_promotion_translation:
        class: Locastic\SyliusCatalogPromotionPlugin\Form\Type\CatalogPromotionTranslationType
        arguments:
            - '%locastic_sylius_catalog_promotion_plugin.model.catalog_promotion_translation.class%'
            - ['sylius']
        tags:
            - { name: form.type }

    locastic.sylius_catalog_promotion_plugin.form.type.catalog_promotion_group:
        class: Locastic\SyliusCatalogPromotionPlugin\Form\Type\CatalogPromotionGroupType
        arguments:
            - '%locastic_sylius_catalog_promotion_plugin.model.catalog_promotion_group.class%'
            - ['sylius']
        tags:
            - { name: form.type }

    locastic.sylius_catalog_promotion_plugin.form.type.catalog_promotion_group_collection:
            class: Locastic\SyliusCatalogPromotionPlugin\Form\Type\CatalogPromotionGroupCollectionType
            arguments:
                - '%locastic_sylius_catalog_promotion_plugin.model.catalog_promotion_group.class%'
                - ['sylius']
            tags:
                - { name: form.type }