sylius_resource:
    resources:
        locastic.sylius_catalog_promotion_plugin.catalog_promotion:
            driver: doctrine/orm
            classes:
                model: Locastic\SyliusCatalogPromotionPlugin\Entity\CatalogPromotion
                form: Locastic\SyliusCatalogPromotionPlugin\Form\Type\CatalogPromotionType
            translation:
                classes:
                    model: Locastic\SyliusCatalogPromotionPlugin\Entity\CatalogPromotionTranslation
                    form: Locastic\SyliusCatalogPromotionPlugin\Form\Type\CatalogPromotionTranslationType