sylius_resource:
    resources:
        locastic_sylius_catalog_promotion_plugin.catalog_promotion:
            driver: doctrine/orm
            classes:
                model: Locastic\SyliusCatalogPromotionPlugin\Entity\CatalogPromotion
                form: Locastic\SyliusCatalogPromotionPlugin\Form\Type\CatalogPromotionType
                repository: Locastic\SyliusCatalogPromotionPlugin\Repository\CatalogPromotionRepository
            translation:
                classes:
                    model: Locastic\SyliusCatalogPromotionPlugin\Entity\CatalogPromotionTranslation
                    form: Locastic\SyliusCatalogPromotionPlugin\Form\Type\CatalogPromotionTranslationType

        locastic_sylius_catalog_promotion_plugin.catalog_promotion_group:
            driver: doctrine/orm
            classes:
                model: Locastic\SyliusCatalogPromotionPlugin\Entity\CatalogPromotionGroup
                form: Locastic\SyliusCatalogPromotionPlugin\Form\Type\CatalogPromotionGroupType
                repository: Locastic\SyliusCatalogPromotionPlugin\Repository\CatalogPromotionGroupRepository

        locastic_sylius_catalog_promotion_plugin.promotion_action:
            driver: doctrine/orm
            classes:
                model: Locastic\SyliusCatalogPromotionPlugin\Entity\PromotionAction
                form: Locastic\SyliusCatalogPromotionPlugin\Form\Type\PromotionActionType

        locastic_sylius_catalog_promotion_plugin.catalog_banner_image:
            driver: doctrine/orm
            classes:
                model: Locastic\SyliusCatalogPromotionPlugin\Entity\CatalogBannerImage
                form: Locastic\SyliusCatalogPromotionPlugin\Form\Type\CatalogBannerImageType

sylius_product:
    resources:
        product:
            classes:
                model: Locastic\SyliusCatalogPromotionPlugin\Entity\Product
        product_variant:
            classes:
                model: Locastic\SyliusCatalogPromotionPlugin\Entity\ProductVariant
sylius_core:
    resources:
        channel_pricing:
            classes:
                model: Locastic\SyliusCatalogPromotionPlugin\Entity\ChannelPricing
                repository: Locastic\SyliusCatalogPromotionPlugin\Repository\ChannelPricingRepository