app_admin_catalog_promotion:
    resource: 'routing/admin.yml'
    prefix: 'admin'

sylius_admin_dashboard:
    path: /kurcic
    defaults:
        _controller: sylius.controller.admin.dashboard:indexAction