imports:
    - { resource: "services/forms.yml" }

services:
    sylius_catalog_promotion_plugin.menu.catalog:
        class: Locastic\SyliusCatalogPromotionPlugin\Menu\AdminMenuListener
        tags:
            -
                name: kernel.event_listener
                event: sylius.menu.admin.main
                method: addAdminMenuItems