imports:
    - { resource: "services/forms.yml" }

services:
    locastic_sylius_catalog_promotion_plugin.menu.catalog:
        class: Locastic\SyliusCatalogPromotionPlugin\Menu\AdminMenuListener
        tags:
            -
                name: kernel.event_listener
                event: sylius.menu.admin.main
                method: addAdminMenuItems

    locastic_sylius_catalog_promotion_plugin.custom_factory.catalog_promotion_group:
        class: Locastic\SyliusCatalogPromotionPlugin\Factory\CatalogPromotionGroupFactory
        public: false
        decorates: locastic_sylius_catalog_promotion_plugin.factory.catalog_promotion_group
        arguments: ['@locastic_sylius_catalog_promotion_plugin.custom_factory.catalog_promotion_group.inner']

    locastic.sylius_catalog_promotion_plugin.promotion.processor.catalog_promotion_processor:
        class: Locastic\SyliusCatalogPromotionPlugin\Promotion\Processor\CatalogPromotionProcessor
        arguments:
            - '@locastic.sylius_catalog_promotion_plugin.provider.channel_pricing_provider'
            - '@?'

#checkers
    locastic_sylius_catalog_promotion_plugin.promotion.checker.has_product_rule_checker:
        class: Locastic\SyliusCatalogPromotionPlugin\Promotion\Checker\HasProductRuleChecker
        tags:
            -
                name: locastic_sylius_catalog_promotion_plugin.rule_checker
                type: has_product
                label: Product is one of
                form.type: Sylius\Bundle\CoreBundle\Form\Type\Promotion\Rule\ContainsProductConfigurationType

#providers
    locastic.sylius_catalog_promotion_plugin.provider.channel_pricing_provider:
        class: Locastic\SyliusCatalogPromotionPlugin\Provider\ChannelPricingProvider
        arguments: ['@sylius.factory.channel_pricing']

#commands
    locastic.sylius_catalog_promotion_plugin.command.refresh_catalog_promotions_command:
        class: Locastic\SyliusCatalogPromotionPlugin\Command\RefreshCatalogPromotionsCommand
        tags:
            - { name: console.command }